//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetARoom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmenityForHotel
    {
        public int Id { get; set; }
        public int HotelId { get; set; }
        public int AmenityTypeId { get; set; }
    
        public virtual Amenity Amenity { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
