//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetARoom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Payment = new HashSet<Payment>();
            this.ReviewForBooking = new HashSet<ReviewForBooking>();
        }
    
        public int BookingId { get; set; }
        public int UserId { get; set; }
        public int RoomId { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.DateTime BookingDateFrom { get; set; }
        public System.DateTime BookingDateTo { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewForBooking> ReviewForBooking { get; set; }
    }
}
