//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetARoom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creditcard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Creditcard()
        {
            this.PaymentTypeForUser = new HashSet<PaymentTypeForUser>();
        }
    
        public int CreditcardId { get; set; }
        public string Hash { get; set; }
        public string CreditcardHolderName { get; set; }
        public System.DateTime CreditcardValidUntil { get; set; }
        public string CreditcardNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentTypeForUser> PaymentTypeForUser { get; set; }
    }
}
